spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver



mybatis:
  # mybatis配置
  # 配置映射类所在包名
  type-aliases-package: com.example.demo.entity.domain
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
      - mapping/*.xml


